apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: springbootdemo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springbootdemo-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10

#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: springbootdemo-hpa
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: springbootdemo-deployment
#  minReplicas: 2
#  maxReplicas: 10
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 50
